# This workflow runs update-readme.py which updates README.md file.

name: Update README

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi # requirements.txt 설치
    - name: Run update_readme.py
      working-directory: auto-readme # 실행할 폴더
      run: |
        python update_readme.py
    - name: Commit changes
      run: |
        git config --global user.name 'woodywarhol9'
        git config --global user.email 'woodywarhol9@gmail.com'
        git add -A
        git commit -am "auto-update README.md"
    - name: Push changes
      run: |
        git push
